In [17]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score
import seaborn as sns
import matplotlib.pyplot as plt

In [18]:
train=pd.read_csv("train.csv")
train

RowNumber  CustomerId     Surname  CreditScore Geography  Gender  Age  \
0           551    15806307   Trevisano          720     Spain    Male   38   
1          6897    15709621      Martin          682    France  Female   54   
2          4588    15619340      Palmer          672    France  Female   31   
3           291    15620746  Napolitani          592     Spain  Female   40   
4          1673    15646372         Yao          753     Spain    Male   42   
...         ...         ...         ...          ...       ...     ...  ...   
7995       5345    15584532          Yu          568    France  Female   35   
7996       5837    15606641        Liao          602   Germany  Female   45   
7997       7335    15739692       Ferri          679     Spain  Female   43   
7998       9552    15791373     Worsnop          715    France    Male   38   
7999        178    15739931      Ibekwe          600    France  Female   42   

      Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0          5  114051.97              2          0               1   
1          4   62397.41              1          1               0   
2          5  119903.67              1          1               1   
3          4  104257.86              1          1               0   
4          5  120387.73              1          0               1   
...      ...        ...            ...        ...             ...   
7995       6  121079.60              2          1               1   
7996       7  145846.07              1          1               0   
7997       5  132810.01              1          1               0   
7998       4  118729.45              1          0               0   
7999       5   62397.41              1          0               0   

      EstimatedSalary  Exited  
0           107577.29       0  
1           113088.60       1  
2           132925.17       0  
3           110857.33       0  
4           126378.57       0  
...               ...     ...  
7995        124890.50       1  
7996         99276.02       0  
7997        130780.85       1  
7998         95484.52       0  
7999         66315.00       0  

[8000 rows x 14 columns]

In [19]:
train["NumOfProducts"].value_counts()

1    4039
2    3697
3     215
4      49
Name: NumOfProducts, dtype: int64

In [20]:
data=train.drop(columns=["RowNumber","CustomerId","Surname"]) #拿掉較不重要的特徵
data=pd.get_dummies(data,columns=["Geography","Gender","NumOfProducts"]) #將類別型資料已one-hot encoding處理
data

CreditScore  Age  Tenure    Balance  HasCrCard  IsActiveMember  \
0             720   38       5  114051.97          0               1   
1             682   54       4   62397.41          1               0   
2             672   31       5  119903.67          1               1   
3             592   40       4  104257.86          1               0   
4             753   42       5  120387.73          0               1   
...           ...  ...     ...        ...        ...             ...   
7995          568   35       6  121079.60          1               1   
7996          602   45       7  145846.07          1               0   
7997          679   43       5  132810.01          1               0   
7998          715   38       4  118729.45          0               0   
7999          600   42       5   62397.41          0               0   

      EstimatedSalary  Exited  Geography_France  Geography_Germany  \
0           107577.29       0                 0                  0   
1           113088.60       1                 1                  0   
2           132925.17       0                 1                  0   
3           110857.33       0                 0                  0   
4           126378.57       0                 0                  0   
...               ...     ...               ...                ...   
7995        124890.50       1                 1                  0   
7996         99276.02       0                 0                  1   
7997        130780.85       1                 0                  0   
7998         95484.52       0                 1                  0   
7999         66315.00       0                 1                  0   

      Geography_Spain  Gender_Female  Gender_Male  NumOfProducts_1  \
0                   1              0            1                0   
1                   0              1            0                1   
2                   0              1            0                1   
3                   1              1            0                1   
4                   1              0            1                1   
...               ...            ...          ...              ...   
7995                0              1            0                0   
7996                0              1            0                1   
7997                1              1            0                1   
7998                0              0            1                1   
7999                0              1            0                1   

      NumOfProducts_2  NumOfProducts_3  NumOfProducts_4  
0                   1                0                0  
1                   0                0                0  
2                   0                0                0  
3                   0                0                0  
4                   0                0                0  
...               ...              ...              ...  
7995                1                0                0  
7996                0                0                0  
7997                0                0                0  
7998                0                0                0  
7999                0                0                0  

[8000 rows x 17 columns]

In [21]:
std=StandardScaler() #連續型以標準化處理
data[["CreditScore","Age","Tenure","Balance","EstimatedSalary"]]=std.fit_transform(data[["CreditScore","Age","Tenure","Balance","EstimatedSalary"]])
data

CreditScore       Age    Tenure   Balance  HasCrCard  IsActiveMember  \
0        1.509906 -0.663721  0.339933  0.428978          0               1   
1        0.866637  1.465241 -0.445812 -1.214512          1               0   
2        0.697356 -1.595141  0.339933  0.615161          1               1   
3       -0.656894 -0.397600 -0.445812  0.117359          1               0   
4        2.068534 -0.131480  0.339933  0.630562          0               1   
...           ...       ...       ...       ...        ...             ...   
7995    -1.063169 -1.062901  1.125677  0.652575          1               1   
7996    -0.487612  0.267700  1.911421  1.440568          1               0   
7997     0.815853  0.001580  0.339933  1.025801          1               0   
7998     1.425266 -0.663721 -0.445812  0.577801          0               0   
7999    -0.521469 -0.131480  0.339933 -1.214512          0               0   

      EstimatedSalary  Exited  Geography_France  Geography_Germany  \
0            0.304927       0                 0                  0   
1            0.529787       1                 1                  0   
2            1.339115       0                 1                  0   
3            0.438752       0                 0                  0   
4            1.072015       0                 0                  0   
...               ...     ...               ...                ...   
7995         1.011302       1                 1                  0   
7996        -0.033763       0                 0                  1   
7997         1.251627       1                 0                  0   
7998        -0.188456       0                 1                  0   
7999        -1.378566       0                 1                  0   

      Geography_Spain  Gender_Female  Gender_Male  NumOfProducts_1  \
0                   1              0            1                0   
1                   0              1            0                1   
2                   0              1            0                1   
3                   1              1            0                1   
4                   1              0            1                1   
...               ...            ...          ...              ...   
7995                0              1            0                0   
7996                0              1            0                1   
7997                1              1            0                1   
7998                0              0            1                1   
7999                0              1            0                1   

      NumOfProducts_2  NumOfProducts_3  NumOfProducts_4  
0                   1                0                0  
1                   0                0                0  
2                   0                0                0  
3                   0                0                0  
4                   0                0                0  
...               ...              ...              ...  
7995                1                0                0  
7996                0                0                0  
7997                0                0                0  
7998                0                0                0  
7999                0                0                0  

[8000 rows x 17 columns]

In [22]:
y=data["Exited"].values #分出x跟y
x=data.drop(columns=["Exited"]).values

In [23]:
test=pd.read_csv("test.csv") #以同樣方式處理測試集
test=test.drop(columns=["RowNumber","CustomerId","Surname"])
test=pd.get_dummies(test,columns=["Geography","Gender","NumOfProducts"])
test[["CreditScore","Age","Tenure","Balance","EstimatedSalary"]]=std.fit_transform(test[["CreditScore","Age","Tenure","Balance","EstimatedSalary"]])
test

CreditScore       Age    Tenure   Balance  HasCrCard  IsActiveMember  \
0        1.609183 -0.508456 -1.222346 -1.272730          0               0   
1        0.528128 -0.112514 -1.222346  0.915085          1               0   
2       -1.401138 -1.168361  1.184637 -1.272730          1               1   
3        1.692341 -0.112514 -1.222346 -0.489610          1               0   
4       -1.600717  0.943333  1.184637 -1.272730          1               1   
...           ...       ...       ...       ...        ...             ...   
1995    -0.020715 -1.036380  1.184637 -1.272730          1               1   
1996     0.162233 -0.244495  0.382309 -0.121318          1               0   
1997    -1.351243  0.415410 -1.222346  0.552459          1               1   
1998    -0.453136  0.151448  1.986964 -1.272730          1               1   
1999    -0.236926 -1.432322  0.382309  0.117487          1               0   

      EstimatedSalary  Geography_France  Geography_Germany  Geography_Spain  \
0            0.263584                 1                  0                0   
1            1.077935                 1                  0                0   
2           -0.887917                 1                  0                0   
3            1.502999                 0                  0                1   
4            1.468965                 1                  0                0   
...               ...               ...                ...              ...   
1995        -0.148555                 1                  0                0   
1996         0.404264                 0                  1                0   
1997         0.702602                 1                  0                0   
1998         1.175787                 0                  0                1   
1999         0.180685                 0                  1                0   

      Gender_Female  Gender_Male  NumOfProducts_1  NumOfProducts_2  \
0                 1            0                1                0   
1                 0            1                1                0   
2                 0            1                0                1   
3                 1            0                1                0   
4                 1            0                1                0   
...             ...          ...              ...              ...   
1995              0            1                0                1   
1996              0            1                0                1   
1997              1            0                0                1   
1998              1            0                0                1   
1999              1            0                1                0   

      NumOfProducts_3  NumOfProducts_4  
0                   0                0  
1                   0                0  
2                   0                0  
3                   0                0  
4                   0                0  
...               ...              ...  
1995                0                0  
1996                0                0  
1997                0                0  
1998                0                0  
1999                0                0  

[2000 rows x 16 columns]

## SVM 

### rbf kernel

In [24]:
from sklearn.svm import SVC 
svm=SVC(C=0.8,gamma="auto",kernel="rbf") #調整參數並建模
svm.fit(x,y)

SVC(C=0.8, gamma='auto')

In [25]:
y_pred=svm.predict(x) 
y_pred
print(accuracy_score(y_pred,y))

0.85725


In [26]:
test_pred=svm.predict(test.values) #對測試集進行預測
np.unique(test_pred)

array([0, 1], dtype=int64)

In [27]:
upload=pd.read_csv("upload.csv") 
upload["Exited"]=test_pred
upload["Exited"].value_counts()

0    1807
1     193
Name: Exited, dtype: int64

In [28]:
upload.to_csv("upload_svmrbf.csv") #將預測結果加入excel檔

### polynomial kernel

In [29]:
from sklearn.svm import SVC
svm=SVC(C=1,gamma="scale",kernel="poly") #調整參數並建模
svm.fit(x,y)

SVC(C=1, kernel='poly')

In [30]:
y_pred=svm.predict(x)
y_pred
print(accuracy_score(y_pred,y))

0.866625


In [31]:
test_pred=svm.predict(test.values) #對測試集進行預測
np.unique(test_pred)

array([0, 1], dtype=int64)

In [32]:
upload=pd.read_csv("upload.csv")
upload["Exited"]=test_pred
upload["Exited"].value_counts()

0    1778
1     222
Name: Exited, dtype: int64

In [33]:
upload.to_csv("upload_svmpoly.csv") #將預測結果加入excel檔

## Decision Tree

In [34]:
from sklearn import tree
clf=tree.DecisionTreeClassifier() #調整參數並建模
clf.fit(x,y)

DecisionTreeClassifier()

In [35]:
y_pred=clf.predict(x)
y_pred
print(accuracy_score(y_pred,y))

1.0


In [36]:
test_pred=clf.predict(test.values) #對測試集進行預測
np.unique(test_pred)

array([0, 1], dtype=int64)

In [37]:
upload=pd.read_csv("upload.csv")
upload["Exited"]=test_pred
upload["Exited"].value_counts()

0    1590
1     410
Name: Exited, dtype: int64

In [38]:
upload.to_csv("upload_tree.csv") #將預測結果加入excel檔

## Random Forest

In [39]:
from sklearn.ensemble import RandomForestClassifier 
rfc=RandomForestClassifier() #調整參數並建模
rfc.fit(x,y)

RandomForestClassifier()

In [40]:
y_pred=rfc.predict(x)
y_pred
print(accuracy_score(y_pred,y))

1.0


In [41]:
test_pred=rfc.predict(test.values) #對測試集進行預測
np.unique(test_pred)

array([0, 1], dtype=int64)

In [42]:
upload=pd.read_csv("upload.csv")
upload["Exited"]=test_pred
upload["Exited"].value_counts()

0    1729
1     271
Name: Exited, dtype: int64

In [43]:
upload.to_csv("upload_randomforest.csv") #將預測結果加入excel檔

## XGBoost

In [44]:
from xgboost import XGBClassifier as XGB
xgb=XGB(max_depth=4,eta=0.08) #調整參數並建模
xgb.fit(x,y) 

XGBClassifier(base_score=0.5, booster='gbtree', callbacks=None,
              colsample_bylevel=1, colsample_bynode=1, colsample_bytree=1,
              early_stopping_rounds=None, enable_categorical=False, eta=0.08,
              eval_metric=None, feature_types=None, gamma=0, gpu_id=-1,
              grow_policy='depthwise', importance_type=None,
              interaction_constraints='', learning_rate=0.0799999982,
              max_bin=256, max_cat_threshold=64, max_cat_to_onehot=4,
              max_delta_step=0, max_depth=4, max_leaves=0, min_child_weight=1,
              missing=nan, monotone_constraints='()', n_estimators=100,
              n_jobs=0, num_parallel_tree=1, predictor='auto', ...)

In [45]:
y_pred=xgb.predict(x)
y_pred
print(accuracy_score(y_pred,y))

0.874


In [48]:
test_pred=xgb.predict(test.values) #對測試集進行預測
np.unique(test_pred)

array([0, 1])

In [49]:
upload=pd.read_csv("upload.csv")
upload["Exited"]=test_pred
upload["Exited"].value_counts()

0    1736
1     264
Name: Exited, dtype: int64

In [50]:
upload.to_csv("upload_xgboost.csv") #將預測結果加入excel檔